openapi: 3.0.3
info:
  title: PIND
  version: '0.1'
  description: PIND doc description
servers:
  - url: http://127.0.0.1:5000
    variables: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: faq
    description: everything related to FAQs
  - name: ticket
    description: everything about tickets
  - name: staff only
    description: actions that can only be performed by staff
  - name: user
    description: user registration and login
paths:
  /faq:
    description: operations related to faqs
    post:
      security:
        - bearerAuth: []
      tags:
        - faq
        - staff only
      summary: ''
      description: create a new faq (staff only)
      operationId: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                staffId:
                  type: integer
                  example: 4
                ticketId:
                  type: integer
                  example: 12
      responses:
        '201':
          description: return newly created faq
          content:
            application/json:
              examples:
                201 result:
                  value:
                    faqId: 1
                    title: >-
                      Does IIT Madras offer B.Sc in Programming & Data Science
                      on-campus?
                    soltuion: >-
                      No, there is no equivalent on-campus version. IIT Madras
                      has carefully curated this exclusively as an online
                      program.
                    categories:
                      - General
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
    get:
      tags:
        - faq
      summary: ''
      description: get all available faqs
      operationId: ''
      responses:
        '200':
          description: returns list of all faqs
          content:
            application/json:
              examples:
                200 result:
                  value:
                    faqs:
                      - faqId: 1
                        title: >-
                          Does IIT Madras offer B.Sc in Programming & Data
                          Science on-campus?
                        solution: >-
                          No, there is no equivalent on-campus version. IIT
                          Madras has carefully curated this exclusively as an
                          online program.
                        categories:
                          - General
                      - faqId: 23
                        title: >-
                          I ran into an error or issue in the application form. What do I do?
                        solution: >-
                          Please send us your registered email ID and a screenshot of the error / issue with relevant description to support@onlinedegeree.iitm.ac.in
                          If the error is after payment has been made, please forward the confirmation email from Razorpay along with email ID, application number and screenshot with description.
                        categories:
                          - Application
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
  /faq/{faqId}:
    description: operations related to a particular faq
    parameters:
      - name: faqId
        description: id of faq
        required: true
        in: path
        schema:
          type: integer
          example: 4
    put:
      security:
        - bearerAuth: []
      tags:
        - faq
        - staff only
      summary: ''
      description: update a particular faq
      operationId: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newTitle:
                  type: string
                  example: "Does IITM offer B.S in Programming and Data Science on-campus?"
                newSolution:
                  type: string
                  example: "No, IITM does not offer this degree on-campus. This is exclusively online."
                newTags:
                  type: array
                  items:
                    type: string
                  example: [General, Campus]
      responses:
        '200':
          description: return updated faq
          content:
            application/json:
              examples:
                200 result:
                  value:
                    faqId: 4
                    title: >-
                      Does IITM offer B.S in Programming and Data Science on-campus?
                    soltuion: >-
                      No, IITM does not offer this degree on-campus. This is exclusively online.
                    categories:
                      - General
                      - Campus
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
    delete:
      security:
        - bearerAuth: []
      tags:
        - faq
        - staff only
      summary: ''
      description: delete a particular faq
      operationId: ''
      responses:
        '200':
          description: deleted successfully
          content:
            application/json:
              examples:
                200 result:
                  value:
                    status: true
                    message: faq deleted successfully
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: faq not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error