openapi: 3.0.3
info:
  title: PIND 0.1
  description: PIND doc description
  version: '0.1'
servers:
  - url: http://127.0.0.1:5000
    variables: {}
tags:
  - name: ticket
    description: everything about tickets

paths:
  /ticket:
    description: operations related to tickets
    post:
      summary: ''
      description: create a new ticket for a given user id (student only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  example: 2
                deets:
                  type: string
                  example: I am unable to access course XYZ
                date:
                  type: integer
                  example: 1231231
                categories:
                  type: array
                  items:
                    type: string
                  example:
                    - XYZ
                    - Operational
      operationId: ticket1
      responses:
        '201':
          description: sample success response - return newly created ticket
          content:
            application/json:
              examples:
                201 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Open
                    replies: []
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: null
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
    get:
      summary: ''
      description: get paginated tickets for a user
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            description: page number
            example: 1
             
        - in: query
          name: size
          schema: 
            type: integer
            description: maximum tickets in the response
            example: 2
            
      operationId: ticket2
      responses:
        '200':
          description: sample success response - return tickets
          content:
            application/json:
              examples:
                200 result:
                  value:
                    tickets: 
                      - {
                        ticketId: 3,
                        userId: 2,
                        deets: I am unable to  access course XYZ,
                        status: Open,
                        replies: [],
                        likes: 0,
                        categories: [XYZ, Operational],
                        linkedTicket: null,
                          
                      }
                      - {
                        ticketId: 4,
                        userId: 2,
                        deets: Regarding graded assignment,
                        status: Open,
                        replies: [],
                        likes: 2,
                        categories: [Graded],
                        linkedTicket: null,
                      }
                    
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: no tickets found

        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
    
  /ticket/{ticketId}:
    description: Specific ticket details
    get:
      summary: ''
      description: get ticket details by ticketId
      parameters:
      - name: ticketId
        description: id of ticket
        required: true
        in: path
        schema:
          type: integer
          example: 3
        
      operationId: ticketB1
      responses:
        '200':
          description: sample success response - return ticket
          content:
            application/json:
              examples:
                200 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Open
                    replies: []
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: null
                  
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: ticket not found

        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      
      tags:
        - ticket
    put:
      summary: ''
      description: update a given ticket
      parameters:
      - name: ticketId
        description: id of ticket
        required: true
        in: path
        schema:
          type: integer
          example: 3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deets:
                  type: string
                  example: I am unable to access course XYZ since yesterday
                categories:
                  type: array
                  items:
                    type: string
                  example:
                    - XYZ2
                    - Operational
      operationId: ticketB2
      responses:
        '200':
          description: sample success response - return updated ticket
          content:
            application/json:
              examples:
                200 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ2 since yesterday
                    status: Open
                    replies: []
                    likes: 0
                    categories:
                      - XYZ2
                      - Operational
                    linkedTicket: null
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                404 result:
                  value: ticket not found
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
    delete:
      summary: ''
      description: update a given ticket
      parameters:
      - name: ticketId
        description: id of ticket
        required: true
        in: path
        schema:
          type: integer
          example: 3
      
      operationId: ticketB3
      responses:
        '200':
          description: sample success response - deleted successfully
          content:
            application/json:
              examples:
                200 result:
                  value:
                    status: true
                    message: deleted successfully
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        
        '404':
          description: sample not found response
          content:
            application/json:
              examples:
                401 result:
                  value: ticket not found
                  
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
  /ticket/markDuplicate:
    description: operations related to tickets
    put:
      summary: ''
      description: create a new ticket for a given user id (student only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentTicketId:
                  type: integer
                  example: 3
                originalTicketId:
                  type: integer
                  example: 5
      operationId: ticketM1
      responses:
        '201':
          description: sample success response - return ticket marked duplicate
          content:
            application/json:
              examples:
                201 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Resolved
                    replies: []
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: 5
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request
        '401':
          description: sample unauthorized response
          content:
            application/json:
              examples:
                401 result:
                  value: you are not authorized to make this request
        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket
  /ticket/reply:
    put:
      summary: ''
      description: reply to a ticket
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  ticketId: 3
                  type: string
                  example: 'Dear student ABC...'
      operationId: ticketM2
      responses:
        '201':
          description: sample success response - return ticket marked duplicate
          content:
            application/json:
              examples:
                201 result:
                  value:
                    ticketId: 3
                    userId: 2
                    deets: I am unable to  access course XYZ
                    status: Resolved
                    replies: 
                      - { userId : 10,
                       message: 'Dear student ABC...'
                      }
                    likes: 0
                    categories:
                      - XYZ
                      - Operational
                    linkedTicket: 5
        '400':
          description: sample bad request response
          content:
            application/json:
              examples:
                400 result:
                  value: bad request

        '500':
          description: sample internal error response
          content:
            application/json:
              examples:
                500 result:
                  value: internal error
      tags:
        - ticket